DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS employee_product_link CASCADE;
DROP TABLE IF EXISTS access_log CASCADE;

CREATE TABLE IF NOT EXISTS roles
(
    id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS products
(
    id   BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS employees
(
    id        BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    firstName VARCHAR(255) NOT NULL,
    lastName  VARCHAR(255) NOT NULL,
    role_id   BIGINT REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS employee_product_link
(
    link_id     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    employee_id BIGINT REFERENCES employees (id) ON DELETE CASCADE,
    product_id  BIGINT REFERENCES products (id) ON DELETE CASCADE,
    CONSTRAINT unique_link UNIQUE (employee_id, product_id)
);

CREATE TABLE IF NOT EXISTS access_log
(
    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    description      VARCHAR(255) NOT NULL UNIQUE,
    employee_id BIGINT REFERENCES employees (id)
);
